# Generated by Django 3.2.2 on 2021-05-29 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='id',
        ),
        migrations.AlterField(
            model_name='follow',
            name='from_follow',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='from_follow', serialize=False, to='register.account'),
        ),
    ]
