# Generated by Django 3.2.2 on 2021-07-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='type_imo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
