# Generated by Django 3.2.2 on 2021-07-17 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_feedback_type_imo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='to_feed_back',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_feed_back', to='register.file'),
        ),
    ]
