# Generated by Django 3.2.2 on 2021-07-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_feedback_to_feed_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='type_imo',
        ),
    ]
