# Generated by Django 3.2.2 on 2021-07-17 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_remove_feedback_type_imo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=1)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('from_pick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_pick', to='register.account')),
                ('to_pick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_pick', to='register.file')),
            ],
            options={
                'db_table': 'pick',
            },
        ),
    ]
